### Login
POST https://usco.protocolosweb.com/api/auth/login
Content-Type: application/json

{
  "documentNumber": "12345678901",
  "password": "password"
}

### Register
POST https://usco.protocolosweb.com/api/auth/register
Content-Type: application/json

{
  "documentType_id": 1,
  "documentNumber": "12345678907",
  "password": "password",
  "firstname": "Manuel",
  "lastname": "Vega",
  "institutionalEmail": "manuelvega7@insitution.com",
  "country_id": 49
}