### SignIn
POST https://usco.protocolosweb.com/api/auth/signin
Content-Type: application/json

{
  "username": "User name",
  "password": "password"
}

### SignUp
POST https://usco.protocolosweb.com/api/auth/signup
Content-Type: application/json

{
  "documentNumber": 1234567890,
  "email": "user2@domain.com",
  "password": "password",
  "documentType": ""
}