### Get all educational entities
GET https://usco.protocolosweb.com/api/educationalEntities
Authorization: {{token_admin}}

### Get educational entity by id
GET https://usco.protocolosweb.com/api/educationalEntities/{{entityIdToGet}}
Authorization: {{token_admin}}

### Create a educational entity
POST https://usco.protocolosweb.com/api/educationalEntities/
Authorization: {{token_admin}}
Content-Type: application/json

{
  "name":  "USCO",
  "nit":  "1234",
  "foundationYear":  2022,
  "country_id":  49,
  "codigoDepartamento":  41,
  "codigoMunicipio":  41001,
  "city": "Neiva"
}

### Update educational entity by id
PUT https://usco.protocolosweb.com/api/educationalEntities/{{entityIdToGet}}
Authorization: {{token_admin}}
Content-Type: application/json

{
  "name":  "USCO_edit"
}

### Delete educational entity by id
DELETE https://usco.protocolosweb.com/api/educationalEntities/{{entityIdToGet}}
Authorization: {{token_admin}}