### Get all municipios
GET https://usco.protocolosweb.com/api/municipios

### Get municipio by id
GET https://usco.protocolosweb.com/api/municipios/{{municipio_id}}

### Get municipios by departamento_id
GET https://usco.protocolosweb.com/api/departamentos/{{departamento_id}}/municipios