### Get all products
GET http://localhost:3000/api/products

### Get product by id
GET http://localhost:3000/api/products/1

### Create product
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYzODMzMTc0NSwiZXhwIjoxNjM4NDE4MTQ1fQ.klPWK_9UXyNHdYaQISRNGpIeLpRcab6_X_l9KHTL3sI

{
  "name": "MacBook Pro 2021",
  "category": "Apple",
  "price": 2999.99,
  "imgURL": "https://www.apple.com/v/macbook-pro-14-and-16/b/images/overview/keyboard/keyboard__0zc8gxnp2gy2_medium.jpg"
}

### Edit product
PUT http://localhost:3000/api/products/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYzODMzMTc0NSwiZXhwIjoxNjM4NDE4MTQ1fQ.klPWK_9UXyNHdYaQISRNGpIeLpRcab6_X_l9KHTL3sI

{
  "price": 4599.99
}

### Delete product by id
DELETE http://localhost:3000/api/products/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYzODMzMTc0NSwiZXhwIjoxNjM4NDE4MTQ1fQ.klPWK_9UXyNHdYaQISRNGpIeLpRcab6_X_l9KHTL3sI