### Get all roles
GET https://usco.protocolosweb.com/api/roles
Authorization: {{token_admin}}

### Get role by id
GET https://usco.protocolosweb.com/api/roles/{{roleId}}
Authorization: {{token_admin}}