### Get all users
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYzODMzMTc0NSwiZXhwIjoxNjM4NDE4MTQ1fQ.klPWK_9UXyNHdYaQISRNGpIeLpRcab6_X_l9KHTL3sI

### Get user by id
GET http://localhost:3000/api/users/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTYzODMzMTc0NSwiZXhwIjoxNjM4NDE4MTQ1fQ.klPWK_9UXyNHdYaQISRNGpIeLpRcab6_X_l9KHTL3sI