### Get all users
GET https://usco.protocolosweb.com/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzMjY0ODMzfQ.zJ_vMZh5EZ0SXAbdPcNo9sWY97GBM2RvE7ws8E9Pmv4

### Get user by id
GET https://usco.protocolosweb.com/api/users/{{userIdToGet}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzMjY0ODMzfQ.zJ_vMZh5EZ0SXAbdPcNo9sWY97GBM2RvE7ws8E9Pmv4