### Get all users
GET https://usco.protocolosweb.com/api/users
Authorization: {{token_admin}}

### Get user by id
GET https://usco.protocolosweb.com/api/users/{{userIdToGet}}
Authorization: {{token_admin}}

### Create a user
POST https://usco.protocolosweb.com/api/users/
Authorization: {{token_admin}}
Content-Type: application/json

{
  "documentNumber": "1313",
  "documentType_id": 1,
  "password": "contrasena"
}

### Update user by id
PUT https://usco.protocolosweb.com/api/users/{{userIdToGet}}
Authorization: {{token_admin}}
Content-Type: application/json

{
  "gender_id": 1
}

### Delete user by id
DELETE https://usco.protocolosweb.com/api/users/{{userIdToGet}}
Authorization: {{token_admin}}